#!/bin/bash

# COMMIT_EDDITMSG
INPUT_FILE=$1
PATTERN="[^.]+\[[^.]+]+:[^.]{1,}"

START_LINE=`head -n1 $INPUT_FILE`
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, see example: <type>[optional scope]: <description>"
  exit 1
fi